#!/bin/bash
# rax: https://github.com/jverghese/rax

# Shell script based JSON parser.
# TODO: Add build file to inline this script.
. lib/JSON.sh

# Config
# ------------------------------------------------
# The location where credentails are stored
rax_creds=~/.raxcreds
# The location where data is cached (auth token, end points etc)
rax_cache=~/.raxcache

# URLs
auth_endpoint=https://auth.api.rackspacecloud.com/v1.1/auth
dashboard_url=https://sage-preprod.glimpse.rax.io

function retrieveCredentials() {
  if [ -f $rax_creds ]
  then
    creds=$(cat $rax_creds)
    username=$(echo $creds | cut -d ' ' -f1)
    api=$(echo $creds | cut -d ' ' -f2)
  else
    echo "Rax credentials file not found."
    exit 1
  fi
}

function jsonPost() {
  echo "curl -i -H "Content-Type: application/json" -H "Accept: application/json" $*"
}

# Accepts $*: A list of other curl parameters.
function jsonPostWithCreds() {
  curl -s -H "Content-Type: application/json" \
       -H "Accept: application/json" \
       -d '{"credentials": {"username": "'$username'","key": "'$api'"}}' $*
}

# Parses auth response and returns the auth token.
function parseAuthToken() {
  echo $1 | tokenize | parse | \
         egrep '\["auth","token","id"]' | \
         awk -F "\t" '{print $NF}' | tr -d '"'
}

function updateConfigFile() {
  if [ -f $rax_cache ]
  then
    echo "Updating auth token in existing config file."
    rm $rax_cache
    echo $1 >> $rax_cache
  else
    echo "Creating new config file with token."
    echo $1 >> $rax_cache
  fi
}

# Returns auth token from cache.
function getAuthToken() {
  if [ -f $rax_cache ]
  then
    cat $rax_cache
  else
    echo "Auth token not found."
    exit 1
  fi
}

function getServers() {
  res=$(curl -w "\n%{http_code}" -s -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Auth-Token: '$authtoken'' 'https://dfw.servers.api.rackspacecloud.com/v2/657527/servers')
  # Get all lines but the last.
  jsonResponse=$(echo "$res" | sed -n '$!p')
  resCode=$(echo "$res" | tail -1)
  if [ "$resCode" == "401" ]; then
    echo "Your auth key may have expired. Please re-run 'rax auth' or 'rax login'"
  else
    names=$(echo $jsonResponse | tokenize | parse | \
         egrep '\["servers",.*,"name"]' | \
         awk -F "\t" '{print $NF}' |  tr -d '"')
    ids=$(echo $jsonResponse | tokenize | parse | \
         egrep '\["servers",.*,"id"]' | \
         awk -F "\t" '{print $NF}' |  tr -d '"')
  fi
  createCols "$names" "$ids"
}

# Accepts:
# $1: A variable with a multiline string
# $2: A line number
function readLine() {
  echo "$1" | head -n $2 | tail -1
}

function createCols() {
  lines=$(echo "$1" | wc -l)
  printf "%-25s %s\n" "Server name" "ID"
  for (( c=1; c<=$lines; c++ ))
  do
    line1=$(readLine "$1" "$c")
    line2=$(readLine "$2" "$c")
    printf "%-25s %s\n" $line1 $line2
  done
  #while read line; do
    #while read line2; do
      #echo "$line $line2";
    #done <<< "$2"
  #done <<< "$1"
}

# function read input from stdin and write output to the stdout
# caller must take care about where come stdin and where go stdout
# Note: This function is unused.
log()
{
  while read data
  do
      echo "[$(date +"%D %T")] $data"
  done
}

function rax() {
  case $1 in
    "auth")
      authResponse=$(jsonPostWithCreds $auth_endpoint)
      authToken=$(parseAuthToken $authResponse)
      updateConfigFile $authToken;;
    "server")
      authtoken=$(getAuthToken);
      getServers;;
    "dashboard")
      authtoken=$(getAuthToken);
      open "$dashboard_url/sso?authtoken=$authtoken";;
    *)
      echo "Invalid command: $1.";;
  esac
}

retrieveCredentials
rax $1
